# ~/.config/yazi/config.yaml

# Default editor
editor: "nvim"

# Terminal opener for generic files
open:
  # Text files
  "*.txt": "less {file}"
  "*.md": "bat {file} --style=plain"
  "*.json": "jq . {file} | less"

  # PDFs
  "*.pdf": "mupdf {file}"

  # Images
  "*.png": "viu {file}"
  "*.jpg": "viu {file}"
  "*.jpeg": "viu {file}"
  "*.gif": "viu {file}"

  # Videos
  "*.mp4": "mpv --really-quiet --no-terminal {file}"
  "*.mkv": "mpv --really-quiet --no-terminal {file}"

  # Audio
  "*.mp3": "mpv --really-quiet --no-terminal {file}"
  "*.wav": "mpv --really-quiet --no-terminal {file}"

  # Archives
  "*.zip": "unzip -l {file} | less"
  "*.tar.gz": "tar -tzf {file} | less"
  "*.tar": "tar -tf {file} | less"

  # Fallback (any other file)
  "*": "less {file}"

# Preview settings (optional, if Yazi supports previews)
preview:
  pdf: "pdftotext {file} - | head -n 50"
  image: "viu -w 40 {file}"  # width-limited preview

