#!/bin/bash
# Based on http://openweathermap.org/current

API_KEY="f1a50647dd7b320c646cb059a0269ef0"

# Check on http://openweathermap.org/find
CITY_ID="250441"

URGENT_LOWER=0
URGENT_HIGHER=30

# Fallback icons (text-based)
ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="℃"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")

WEATHER_MAIN=$(echo "${WEATHER_INFO}" | jq -r '.weather[0].main')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | jq -r '.main.temp')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${ICON_SNOW} : ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${ICON_RAINY} : ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
  echo "${ICON_STORM} : ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${ICON_CLOUDY} : ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${ICON_SUNNY}  :${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  echo "${ICON_FOG}  :${WEATHER_TEMP}${SYMBOL_CELSIUS}"
else
  echo "${WEATHER_MAIN}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
fi
